#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import openai
import readline
import os
from termcolor import cprint

openai.api_key = os.getenv("OPENAI_API_KEY")

DEBUG = os.getenv("OPENAI_DEBUG_MODE")

SESSION = [
  {"role": "system", "content": "You are a helpful assistant."},
]

def ask_gpt(question: str) -> str:
  generate_user_prompt(question)
  response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    temperature=0.5,
    messages=SESSION
  )
  if DEBUG:
    cprint('[debug]: {} tokens were used.'.format(response.usage.total_tokens), 'red')
  answer = response.choices[0].message.content
  generate_assistant_prompt(answer)
  return answer

def generate_user_prompt(question: str):
  SESSION.append( {"role": "user", "content": question} )

def generate_assistant_prompt(answer: str):
  SESSION.append( {"role": "assistant", "content": answer} )

def main():
  print("Welcome to ChatGPT!")
  cprint('(type "exit" to exit from conversation)', 'grey')
  while True:
    # Get user input
    user_input = input('You: ')

    # Exit if user enters 'exit'
    if user_input.lower() == 'exit':
      break

    # Get GPT response
    gpt_response = ask_gpt(user_input)

    # Print GPT response
    cprint('AI: {}'.format(gpt_response), 'green')

main()
